# Generated by Django 4.1.2 on 2022-10-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=5000)),
                ('fechacreación', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('autor', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('fechaingreso', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('fecharegistro', models.DateTimeField()),
            ],
        ),
    ]
