# Generated by Django 4.1.2 on 2022-10-12 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0003_comentario_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='creador',
        ),
    ]
