# Generated by Django 4.1.2 on 2022-10-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0004_rename_autor_comentario_creador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='fechacreación',
            new_name='fechaCreacion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='fechaingreso',
            new_name='fechaIngreso',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='fecharegistro',
            new_name='fechaRegistro',
        ),
    ]
