# Generated by Django 4.1.2 on 2022-11-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0006_alter_libro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
