# Generated by Django 4.1.2 on 2022-11-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0009_alter_avatar_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
