# Generated by Django 4.1.2 on 2022-11-14 01:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0010_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
